namespace TrainGame.Components;

using System.Collections.Generic;
using System.Drawing; 
using System; 

using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
using Microsoft.Xna.Framework.Input;
using Microsoft.Xna.Framework.Content;

using TrainGame.ECS; 
using TrainGame.Systems;
using TrainGame.Constants;

public static class RegisterComponents {
    public static void All(World w) {
        
        void r<T>() {
            w.AddComponentType<T>(); 
        }

        r<Active>(); 
        r<AddCartButton>(); 
        r<AddCartInterfaceButton>(); 
        r<AmmoHUD>(); 
        r<Armor>();
        r<Background>(); 
        r<Backgrounds>(); 
        r<Body>();
        r<Bullet>(); 
        r<BulletWarning>(); 
        r<Button>(); 
        r<CardinalMovement>(); 
        r<Cart>(); 
        r<CartAssembler>();
        r<City>(); 
        r<CityUI>(); 
        r<ChaseMovePattern>();
        r<ClearLLMessage>(); 
        r<CloseMenuMessage>(); 
        r<Collidable>(); 
        r<Collided>();
        r<CombatReward>(); 
        r<CombatRewardCollectedMessage>(); 
        r<ComingFromCity>();
        r<ConnectCitiesButton>();
        r<CurrentInventory>();
        r<CyclicalMovePattern>();
        r<Damage>(); 
        r<DamagePotion>(); 
        r<Data>(); 
        r<DefaultMovePattern>();
        r<DefaultShootPattern>();
        r<UpgradeDepotButton>(); 
        r<Draggable>(); 
        r<DrawAddCartInterfaceMessage>(); 
        r<DrawBackgroundMessage>(); 
        r<DrawCallback>(); 
        r<DrawCityInterfaceMessage>();
        r<DrawCityMessage>(); 
        r<DrawEmbarkMessage>();  
        r<DrawInterfaceMessage<ElevatorInterfaceData>>();
        r<DrawInterfaceMessage<EquipmentInterfaceData>>(); 
        r<DrawInterfaceMessage<MachineInterfaceData>>();
        r<DrawInterfaceMessage<TravelingInterfaceData>>(); 
        r<DrawInterfaceMessage<UpgradeTrainInterfaceData>>();
        r<DrawInterfaceMessage<ViewProgramInterfaceData>>(); 
        r<DrawInterfaceMessage<VendorInterfaceData>>();
        r<DrawInterfaceMessage<WriteProgramInterfaceData>>(); 
        r<DrawInventoryContainerMessage<Train>>();
        r<DrawLadderMessage>(); 
        r<DrawMachineRequestMessage>(); 
        r<DrawMapMessage>(); 
        r<DrawSetTrainProgramInterfaceMessage>();
        r<DrawToastMessage>();
        r<DrawTrainInterfaceMessage>(); 
        r<ElevatorButton>();
        r<EmbarkButton>(); 
        r<EmbarkedMessage>();
        r<EndVampired>();
        r<Enemy>(); 
        r<EnemySpawner>(); 
        r<EnterInterfaceButton<EquipmentInterfaceData>>(); 
        r<EnterInterfaceButton<MachineInterfaceData>>();
        r<EnterInterfaceButton<UpgradeTrainInterfaceData>>();
        r<EnterInterfaceButton<ViewProgramInterfaceData>>(); 
        r<EnterInterfaceButton<WriteProgramInterfaceData>>(); 
        r<EnterInterfaceInteractable<VendorInterfaceData>>();
        r<EnterInterfaceInteractable<ElevatorInterfaceData>>();
        r<EquipmentData>();
        r<EquipmentSlot<Armor>>();
        r<EquipmentUI>(); 
        r<Frame>(); 
        r<GameClockView>();
        r<GoingToCity>();
        r<GridShootPattern>();
        r<Health>(); 
        r<HeldItem>(); 
        r<HealthPotion>(); 
        r<HitMessage>();
        r<Homing>();
        r<Interactable>(); 
        r<Interactor>();  
        r<Inventory>(); 
        r<InventoryContainer<Train>>(); 
        r<InventoryIndexer<Train>>(); 
        r<Inventory.Item>();
        r<InventoryOrganizeMessage>();
        r<InventoryPosition>();
        r<InventoryUpdatedFlag>();
        r<Ladder>();
        r<Machine>(); 
        r<MachineHeader>();
        r<MachinePriorityStepper>();
        r<MachineRequestButton>(); 
        r<MachineStorageStepper>();
        r<ManualCraftButton>(); 
        r<MapUIFlag>();
        r<MeleeShootPattern>();
        r<Menu>(); 
        r<MovementBounds>();
        r<MoveTiming>(); 
        r<Label>(); 
        r<LinearLayout>(); 
        r<Lines>(); 
        r<LLChild>(); 
        r<LLPageButton>(); 
        r<LoadButton>(); 
        r<Loot>(); 
        r<NextDrawTestButton>();
        r<NextDrawTestControl>(); 
        r<Outline>(); 
        r<ParametricCurve>();
        r<Parrier>();
        r<ParryHPBar>();
        r<PauseButton>(); 
        r<PauseTrainProgramButton>();
        r<Player>(); 
        r<PlayerHUD>(); 
        r<ProgressBar>(); 
        r<PurchaseButton<PurchaseItem>>();
        r<PurchaseButton<ResetHP>>();
        r<RadialShootPattern>();
        r<ReceiveDamageMessage>(); 
        r<RemoveOnCollision>();
        r<RespawnLocation>(); 
        r<SaveButton>(); 
        r<Scene>(); 
        r<ScreenAnchor>(); 
        r<SetInvincibleMessage>();
        r<SetPlayerProgramButton>();
        r<SetTrainProgramButton>(); 
        r<SetTrainProgramInterfaceButton>(); 
        r<Shooter>(); 
        r<ShotgunShootPattern>();
        r<ShotBy>();
        r<ShotMessage>();
        r<SlowTimeButton>();
        r<SpeedTimeButton>(); 
        r<Split>();
        r<Sprite>(); 
        r<Stepper>(); 
        r<StepperButton>(); 
        r<StepperMessage>(); 
        r<TALBody<Train, City>>();
        r<Targetable>();
        r<TempArmor>(); 
        r<TextBox>(); 
        r<TextInput>(); 
        r<Toast>(); 
        r<Train>(); 
        r<TrainAssembler>(); 
        r<TrainEmbarkedMessage>(); 
        r<TrainUI>(); 
        r<TrainYard>(); 
        r<UnpauseButton>(); 
        r<UpgradeFuelConsumptionButton>();
        r<UpgradeInventoryExponentialButton>();
        r<UpgradeMachineButton>(); 
        r<UpgradeMachineProductCountButton>();
        r<UpgradeMachineSpeedButton>();
        r<UpgradeTrainPowerButton>();
        r<Vampired>();
        r<Vampiric>();
        r<Velocity>(); 
    }
}